### PR TITLE
Updating library to .NETStandard2.0

### PR DESCRIPTION
**Pull request by mculhane1**
Hopefully I got everything.  Love this library and it made a project of mine significantly better.

### CODE REVIEW

**Comment by jam40jeff** [comment]
This looks good, but there are a couple things I think we need to figure out.

- Although the AppVeyor build is passing, it is not finding the tests.

- AssemblyInfo.cs has been removed because of the new .csproj file format, but the tooling is using that file to set the correct version number for the NuGet package.  I think we can work around this by adding:

```
<PropertyGroup>
   <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
</PropertyGroup> 
```

to the .csproj file per https://stackoverflow.com/questions/42138418/equivalent-to-assemblyinfo-in-dotnet-core-csproj.

**Comment by mculhane1** [comment]
I'm not familiar with AppVeyor, but it looks like it ran the tests successfully once, and the second time it couldn't find them.

I added changes to the .csproj as suggested later in the stackoverflow link. I bumped the version to 2.0, but feel free to edit that as necessary.

**Comment by jam40jeff** [comment]
I changed some AppVeyor settings and fixed the output assembly name.  If everything checks out OK with this build, I will merge.

**Comment by jam40jeff** [comment]
Also, I believe we should target the lowest netstandard version possible to maximize compatibility.

It looks like netsandard1.0 still compiles.

**Comment by mculhane1** [comment]
All looks good to me, thanks @jam40jeff.

**Comment by mculhane1** [comment]
Looks like this generate the wrong file type. Please ignore

---

Source\MorseCode.ITask\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[MorseCode.ITask]*" -target:"dotnet.exe" -targetargs:"test Source\MorseCode.ITask\Tests" -output:coverage.xml

to 

Source\MorseCode.ITask\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[MorseCode.ITask]*" -target:"dotnet.exe" -targetargs:"test Source\MorseCode.ITask\Tests --collect:'Code Coverage'" -output:coverage.xml
--collect:"Code Coverage"

**Comment by jam40jeff** [comment]
Fixes #2

**Comment by jam40jeff** [comment]
@mculhane1 Thanks for providing this.  The `MorseCode.ITask` 2.0.0 package has just been published with .NET Standard 1.0 and up support.

**Pull request merged**
